### ISSUE TITLE
uint64_t and c89?

### ISSUE THREAD

**Issue by hartwork** [whitfin/siphash-c#2]
Hi!

I came here looking for a C89 implementation of SipHash and found description "A C89 implementation" here. I see it use type `uint64_t`. Doesn't that make it non-C89? Am I missing something?

They way I read http://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdint.h.html, `uint*_t` types are marked `[CX]` for "Extension to the ISO C standard".

Thanks, Sebastian

**Comment by whitfin** [comment]
Aloha!

I'm not entirely sure if I'm completely honest. I was writing this for what I was informed was a C89 environment, and it worked just fine - maybe there were some modifications made?

Would you suggest replacing `uint64_t`? I'm open to it if it would improve compatibility!

Thank you!

**Comment by hartwork** [comment]
Hi!

After [having tried resolving `uint64_t`](https://github.com/libexpat/libexpat/pull/71) for the implementation of SipHash that I went with for libexpat, I cannot really recommend replacing `uint64_t` any more, at least not using that very approach. I let GCC fool me to believe that `-std=c89` and `uint64_t` would go well together, but soon [I was proven wrong](https://github.com/libexpat/libexpat/pull/69). Right now I assume SipHash and c89 out of reach. If you get to true c89 here, that would be unique, I guess.
