### ISSUE TITLE
Cannot hash data containing null bytes / add test covering spec test case

### ISSUE THREAD

**Issue by hartwork** [whitfin/siphash-c#4]
Hi!

[SipHash: a fast short-input PRF (siphash.pdf)](https://131002.net/siphash/siphash.pdf) has a section "Test values" that defines a test case:
> This appendix shows intermediate values of SipHash-2-4 hashing the 15-byte
string 000102...0c0d0e with the 16-byte key 000102...0d0e0f [..] to return a129ca6149be45e5.

Integrating that case into the current test suite of siphash-c would be line ...
```
test(0xa129ca6149be45e5,
    "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f",  /* key */
    "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e",
    2, 4);
```
... but the test fails due to automatic length calculation `len = strlen(data)` and the leading null byte in the data to hash which makes `len = 0`. If I add a length parameter `size_t len` and pass proper values, the spec test case passes, which is nice. Please introduce a length parameter to support null bytes and add the spec test case to the test suite.

Thanks and best
&nbsp;
&nbsp;
Sebastian

**Comment by whitfin** [comment]
@hartwork interesting, nice catch.

Would you like to PR an alternate signature with length included? Then we can just use `strlen(data)` as a best guess in case it isn't provided.

**Comment by hartwork** [comment]
Hi!

With C's lack of default values for arguments, you would need to pass `0` for a length to indicate absence.
Since `char` can be signed or unsigned, I would avoid `char` in favor of `uint8_t` (but that's not c89) altogether, e.g.
```
uint64_t siphash(const uint8_t key[16], const uint8_t * data, size_t data_len, unsigned int c, unsigned int d);
```
Please note the non-optional `const` for [const correctness](https://isocpp.org/wiki/faq/const-correctness#const-ptr-vs-ptr-const) and the `unsigned` for `c` and `d`.

**Comment by jotaro-sama** [comment]
Hello there! I saw this was left unfinished and took the chance to implement all of the changes you discussed. I hope it helps!

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
